runai submit \
  --name test-example \
  --image 10.202.67.207:5000/wds20:example_image \
  --backoff-limit 0 \
  --gpu 1 \
  --cpu 4 \
  --large-shm \
  --run-as-user \
  --host-ipc \
  --project wds20 \
  --volume /nfs/home/wds20/projects/example_runai:/project/ \
  --command -- python3 /project/src/test.py